# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PANDA_HIDE) += panda_hide.o

panda_hide-y := \
	panda_common.o \
	panda_debugger.o \
	panda_frida.o \
	panda_path.o \
	panda_mem.o \
	panda_lsm.o \
	panda_main.o
