#!/usr/bin/env bash
# Fix incomplete Xiaomi OSS trees: create stub Kconfig for missing source "..."
# so kconfig can run. Does NOT invent driver code — options simply won't appear.
# Usage: fix-oss-kconfig.sh <kernel_src>
set -euo pipefail

KERNEL_SRC="${1:-}"
[[ -n "${KERNEL_SRC}" && -d "${KERNEL_SRC}" ]] || {
  echo "Usage: $0 <kernel_src>" >&2
  exit 2
}
KERNEL_SRC="$(cd "${KERNEL_SRC}" && pwd)"
cd "${KERNEL_SRC}"

echo "[+] Scanning for missing Kconfig sources under ${KERNEL_SRC}"

# Known Xiaomi OSS holes (explicit stubs with help text)
declare -A KNOWN_STUBS=(
  ["drivers/misc/hwid/Kconfig"]=$'# SPDX-License-Identifier: GPL-2.0\n# Stub: drivers/misc/hwid not published in MiCode OSS for this branch.\n# Present only so parent Kconfig can source this file.\n'
)

created=0
# Explicit known stubs first
for rel in "${!KNOWN_STUBS[@]}"; do
  if [[ ! -f "${rel}" ]]; then
    mkdir -p "$(dirname "${rel}")"
    printf '%s\n' "${KNOWN_STUBS[$rel]}" > "${rel}"
    echo "  [stub] ${rel}"
    created=$((created+1))
  fi
done

# Generic pass: any source "path/Kconfig" referenced but missing
# Limit to drivers/ arch/ fs/ net/ sound/ security/ to avoid false positives
while IFS= read -r line; do
  # extract path between quotes
  rel="${line#*source \"}"
  rel="${rel%%\"*}"
  [[ "${rel}" == *Kconfig* ]] || continue
  [[ -f "${rel}" ]] && continue
  # only create if parent Kconfig exists somewhere that referenced it — path relative to kernel root
  dir="$(dirname "${rel}")"
  mkdir -p "${dir}"
  cat > "${rel}" <<EOF
# SPDX-License-Identifier: GPL-2.0
# Auto-stub generated by fix-oss-kconfig.sh
# Missing from Xiaomi OSS export: ${rel}
# Empty on purpose — do not enable non-existent drivers.
EOF
  echo "  [auto-stub] ${rel}"
  created=$((created+1))
done < <(rg -N --no-filename -o 'source\s+"[^"]+Kconfig[^"]*"' \
  drivers arch fs net sound security 2>/dev/null | sed 's/.*"\([^"]*\)"/\1/' | sort -u || true)

echo "[+] Created ${created} stub Kconfig file(s)"
